FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y gcc-arm-none-eabi build-essential && \
    mkdir /app

COPY srcs/test.c /app/
WORKDIR /app

# ARM GCC (Newlib)を使用
RUN arm-none-eabi-gcc /app/test.c -o test.out --specs=nosys.specs -lc -lnosys

CMD ["./test.out"] 